version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    commit-message:
      prefix: chore
      include: scope
    reviewers:
      - pmrotule

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
    commit-message:
      prefix: chore
      include: scope
    reviewers:
      - pmrotule
