name: Validate PR title

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  conventional-pr-title:
    name: Conventional commit
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          scopes: |
            deps
            deps-dev
            README
